import { useState } from "react";
import { KenyaMap, type Dataset } from "@debunktech/kenya-map";
import sampleVoterData from "./sampleVoterData.json";

// Real 2022 registered-voter counts per county/constituency/ward, from the
// same IEBC list the data pipeline uses for official codes/names (see
// data/reference/README.md). Generated by
// scripts/generate-demo-sample-data.mjs — re-run that if the reference
// file ever changes. "winner" below is the one made-up dataset, kept only
// to demonstrate categorical (as opposed to numeric-gradient) coloring.
const voterColors = { scale: ["#eff6ff", "#1d4ed8"], noData: "#e5e5e5" };
const formatVoters = (v: number | string) => Number(v).toLocaleString();

const datasets: Dataset[] = [
  {
    id: "voters-county",
    label: "Registered voters (2022, county)",
    level: "county",
    values: sampleVoterData.countyVoters,
    colors: voterColors,
    format: formatVoters,
  },
  {
    id: "voters-constituency",
    label: "Registered voters (2022, constituency)",
    level: "constituency",
    values: sampleVoterData.constituencyVoters,
    colors: voterColors,
    format: formatVoters,
  },
  {
    id: "voters-ward",
    label: "Registered voters (2022, ward)",
    level: "ward",
    values: sampleVoterData.wardVoters,
    colors: voterColors,
    format: formatVoters,
  },
  {
    id: "winner",
    label: "Winning party (made-up sample)",
    level: "constituency",
    values: [
      { code: "288", value: "ODM" },
      { code: "274", value: "UDA" },
      { code: "275", value: "ODM" },
      { code: "279", value: "UDA" },
    ],
    colors: { categories: { ODM: "#f97316", UDA: "#facc15" }, noData: "#e5e5e5" },
  },
];

export function App() {
  const [activeDatasetId, setActiveDatasetId] = useState("voters-county");

  return (
    <div style={{ maxWidth: 900, margin: "2rem auto" }}>
      <h1>kenya-map demo</h1>
      <p style={{ color: "#525252", fontSize: 14 }}>
        Registered-voter datasets use real 2022 IEBC figures (Independent Electoral and Boundaries Commission, Kenya).
        "Winning party" is a made-up sample.
      </p>
      <div style={{ height: 600, border: "1px solid #e5e5e5" }}>
        {/* /data is served locally by demo/vite.config.ts's serveRepoData
            plugin, standing in for the jsDelivr URL a real consumer's
            boundariesBaseUrl would point at once this package is tagged. */}
        <KenyaMap
          boundariesBaseUrl="/data"
          datasets={datasets}
          activeDatasetId={activeDatasetId}
          onDatasetChange={setActiveDatasetId}
          showDatasetSwitcher
          showLegend
        />
      </div>
    </div>
  );
}
