import type { Dataset, PointLayer } from "@debunktech/kenya-map";
import sampleVoterData from "./sampleVoterData.json";

// Real 2022 registered-voter counts per county/constituency/ward, from the
// same IEBC list the data pipeline uses for official codes/names (see
// data/reference/README.md). Generated by
// scripts/generate-demo-sample-data.mjs — re-run that if the reference
// file ever changes.
const voterColors = { scale: ["#eff6ff", "#1d4ed8"], noData: "#e5e5e5" };
export const formatVoters = (v: number | string) => Number(v).toLocaleString();

export const voterDatasets: Dataset[] = [
  {
    id: "voters-county",
    label: "Registered voters (2022, county)",
    level: "county",
    values: sampleVoterData.countyVoters,
    colors: voterColors,
    format: formatVoters,
  },
  {
    id: "voters-constituency",
    label: "Registered voters (2022, constituency)",
    level: "constituency",
    values: sampleVoterData.constituencyVoters,
    colors: voterColors,
    format: formatVoters,
  },
  {
    id: "voters-ward",
    label: "Registered voters (2022, ward)",
    level: "ward",
    values: sampleVoterData.wardVoters,
    colors: voterColors,
    format: formatVoters,
  },
];

// The one made-up dataset in this demo (everything else uses real IEBC
// figures) — kept only to show categorical, as opposed to numeric-
// gradient, coloring.
export const winnerDataset: Dataset = {
  id: "winner",
  label: "Winning party (made-up sample)",
  level: "constituency",
  values: [
    { code: "288", value: "ODM" },
    { code: "274", value: "UDA" },
    { code: "275", value: "ODM" },
    { code: "279", value: "UDA" },
  ],
  colors: { categories: { ODM: "#f97316", UDA: "#facc15" }, noData: "#e5e5e5" },
};

// Made-up sample point layers — coordinates are real city locations,
// labels/data are invented.
export const pointLayers: PointLayer[] = [
  {
    id: "stories",
    label: "Story locations (sample)",
    color: "#2563eb",
    categoryColors: { water: "#0891b2", health: "#16a34a", governance: "#ca8a04" },
    points: [
      { id: "s1", lat: -1.2921, lng: 36.8219, label: "Nairobi water story", category: "water", data: { url: "/stories/water" } },
      { id: "s2", lat: -4.0435, lng: 39.6682, label: "Mombasa port investigation", category: "governance", data: { url: "/stories/port" } },
      { id: "s3", lat: -0.0917, lng: 34.768, label: "Kisumu clinic shortage", category: "health", data: { url: "/stories/clinic" } },
      { id: "s4", lat: -0.3031, lng: 36.08, label: "Nakuru land dispute", category: "governance", data: { url: "/stories/land" } },
    ],
  },
  {
    id: "offices",
    label: "Field offices (sample)",
    color: "#db2777",
    points: [
      { id: "o1", lat: 0.5143, lng: 35.2698, label: "Eldoret field office" },
      { id: "o2", lat: -1.0396, lng: 37.0834, label: "Nyeri field office" },
    ],
  },
];
